server:
#  host: localhost
  host: 192.168.243.136
  port: 8000
  static_dir: static
postgres:
  host: 192.168.88.132
  port: 5432
  user: postgres
  password: root
  database: czq
redis:
  host: 192.168.88.132
  port: 6379
  password: root
  db: 0
jwt:
  secret: czq

